mosquitto_shadow: ENC[AES256_GCM,data:06GNNh7uNWod/pRNc4cm0mvVXCPfGj0GLGZOrb3At5nN88LKgl7iYs+13AILP3zGfX2MD4p21q8ik1QJmATGr2rK5wU+7Ko2rdqBWt0Pgo1YxQnTleXAn5gX5/NmqbwAU+Nn8ssdS4yqYArP8mYCww==,iv:bua54LkwvTJVrGzJ/etkdeH1KaqnuLAEFopkRedq90Y=,tag:FVhNj7R0SHJ5+QEf0sjWsQ==,type:str]
mosquitto_pass_env: ENC[AES256_GCM,data:9ajX4CftjGnJBy+UG5nx/lwv6WoRYPH6OequV8xLudvr1yFwWkePfr8Oc2hwUqV8HXCWH+Sr+XYxcCA3vYNy5m58RT8zYhcuoBp0ue8=,iv:atFPwdtPPxSVwGDZ+iLQJirWFp9eKX9rHdno6i+hqD0=,tag:vbGcVjRN+ZiLQj6H844B+Q==,type:str]
homeassistant: ENC[AES256_GCM,data:rt2wj6X1sT+37KYFg1U/pV/XyNmHNPS/T1ERuT7SasohGgdFmMxnbLLF5jl9w/dHd+ao41Kh,iv:ReUvRtzgK/Ln3eglD0zZHWldhbhg7pbAsa0OfFIwMAQ=,tag:kl0dylkZ7QfDiI1ceBNFrg==,type:str]
sops:
    age:
        - recipient: age1az03mzkvy5jfh24helqkyveydvrzd6dyg4ejm0e4easajmn7yyxqvc5fx4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbUZVWHpMSlRVWFdsQ251
            YnhLTXpVMEpkcDh0azl4Tm85RmhHL2xTbERRClJXQ3M2bG81YUxJdGlPeitMUytV
            NzhIU2JqL0ZBWFo3aGpyL2RCK040bkEKLS0tIDY1MDV1bi9oM0VjWDlKdTJQUzhq
            Y1lQZWlwNWxSZWE3V2MwUVp6YTBneTgKMkF1BfnnJ5WCtJvviGmd0WeRW6KBhJDm
            aGdiH63N3cgBhEHnnO4Qc1SihQTdebTOgQyYwnMW9FOQNpE0jw3Jcg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAJtnInq4+GgnLhx7Z3FhsKBO0ReSPilFx05Kxv2i8m5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEhSYmRMdyBlUkpm
            NFYyaHdtZGhIT1ZiUHI3ZDZrOFFPdTlreEpQS1dxMG9GUVBRVEdNCkNEQVUzOFdP
            TndhYk00NWVuQWNxRjh0WmkveE5zcGVidTlWeHdUa3lheWMKLS0tIEU4dTBhQjFU
            eGQ5L0dVczg4d3RCTHdGTGR5R0d4OWVEdDl4WDJFLzA2MXcK99PG3QEogsib2Fnt
            sRR+LgQMpxJ4pAkhWYzgRLn7mDoSfPCIY02mCAc8SoMsyeA2M61wkgjYUol897Dz
            98WI4A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mkqq4xp0jx03ruzadg7xfyp3qg4q9kv7hg9g303mdr9uhas5cs6q9ppzhk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMOTNtU2RwTXVGaU9QR1JB
            dWpNR1k4TjdiSk5ISHhNaUNuWkRjY0R5Y1NVCklsWEZOMHFEVDRLZTE2M3FrY1g5
            ZjFoSkM0ZjYyWUp1d2F2TXNCWFJ0Vk0KLS0tIDdJMXZ6QlVNRGpDSHVFUkVHWmVY
            WkEybUppL2tpd0RhVkNsdXdWK1VxWXMKDgf82Pbvk1u7z+OFC9d+/iAFFWS6i6NT
            lrPUVb+KEmZfg8gTwJS8QtbgejZFRw6M3vnoHE7lrsgH2MLR9R+xug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T11:43:09Z"
    mac: ENC[AES256_GCM,data:WAiy3oug2U6BhoiufaqgLBsqzzFfYaScGwa+aBood8zegJNsoCa5LsEXCdHKgQyTfXsuoW2ZvWVH+nS7tUlO/F9TJAfRL5MZ28Xat93tsEGi2G5igN+md3V2zEq8dCvIU4CmGP+wEEQugIUcOkvpDTdftdYToAGBawhfllSDWTg=,iv:kBKIW1RfQ/GmTOohXKcJNeSEh6AnMwHx7s3ehNcBl7A=,tag:Ksrmn+DG8aNG5F/mdSGPZA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
